name: online_school_bmstu
services:
  redis:
    container_name: school_redis
    image: redis:latest
    restart: always
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache:/data
  postgres:
    container_name: school_postgres
    image: postgres:15.3-alpine
    restart: always
    env_file: ".env"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg-dump:/docker-entrypoint-initdb.d
volumes:
  pgdata:
  cache: